package com.CustomException;

public class CustomException {

	public static void main(String[] args) {
		System.out.println("Inside Main Method ...");
		m1();
	}

	static void m1() {
		System.out.println("Inside m1 Method...");
		try {
			int a;
			Scanner s = new Scanner(System.in);
			
		} catch (Exception e) {
			
		}
	}
}
