package com.CustomException;

public class CustomException {

	public static void main(String[] args) {
		System.out.println("Inside Main Method ...");
		m1();
	}

}
